services:
  stack-game-client:
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: always
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
    networks:
      - stack-game-net
    tty: true

networks:
  stack-game-net:
