services:
  tower-drop-client:
    build:
      context: ./
      dockerfile: Dockerfile.development
    restart: always
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - 3000:3000
    networks:
      - tower-drop-net
    tty: true

networks:
  tower-drop-net:
