services:
  stack-game-client:
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:80
    networks:
      - stack-game-net

networks:
  stack-game-net:
