services:
  tower-drop-client:
    build:
      context: ./
      dockerfile: Dockerfile.production
    restart: always
    ports:
      - 3000:80
    networks:
      - tower-drop-net

networks:
  tower-drop-net:
